platform :ios, '8.0'

use_frameworks!

target 'Logoji_Example' do
  pod 'Logoji', :path => '../'

  target 'Logoji_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
